#!/usr/bin/env bash
# Termux bootstrap for reaching the VPS over Tailscale (userspace, no VPN slot).
# Idempotent. Read android/README.md for the why. Run inside Termux.
set -euo pipefail

VPS_IP=100.114.65.15
VPS_USER=openclaw

pkg install -y openssh curl proxychains-ng

# Phone's own ssh key (revocable per device on the VPS).
[ -f ~/.ssh/id_ed25519 ] || ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N "" -C "termux-$(hostname 2>/dev/null || echo phone)"

# Userspace tailscale (community build; stock tailscaled is blocked by Android netlink policy).
command -v tailscaled-start >/dev/null 2>&1 \
  || curl -fsSL https://raw.githubusercontent.com/bropines/tailscale-termux-cli/main/remote-install.sh | bash
pgrep -x tailscaled >/dev/null || tailscaled-start >/dev/null 2>&1 || true
sleep 2

# proxychains → the tailscale SOCKS5 proxy (credentials generated by tailscaled-start).
# shellcheck source=/dev/null
. ~/.tailscale/socks5.env
cat > "$PREFIX/etc/proxychains.conf" <<CONF
strict_chain
quiet_mode
proxy_dns
[ProxyList]
socks5 127.0.0.1 1055 $TS_SOCKS5_USER $TS_SOCKS5_PASS
CONF

# ssh host alias (proxychains does the routing, so plain HostName is fine).
mkdir -p ~/.ssh && chmod 700 ~/.ssh
grep -q '^Host vps$' ~/.ssh/config 2>/dev/null \
  || printf 'Host vps\n  HostName %s\n  User %s\n' "$VPS_IP" "$VPS_USER" >> ~/.ssh/config

# Shell helpers + tailscaled auto-start on every new Termux session.
touch ~/.bashrc
grep -q "alias vps=" ~/.bashrc || echo "alias vps='proxychains4 ssh vps'" >> ~/.bashrc
grep -q "alias vnc=" ~/.bashrc || echo "alias vnc='proxychains4 ssh -N -L 5901:$VPS_IP:5901 vps'" >> ~/.bashrc
grep -q "tailscaled-start" ~/.bashrc || echo 'pgrep -x tailscaled >/dev/null || tailscaled-start >/dev/null 2>&1' >> ~/.bashrc

echo
echo "Done. Next (once):"
echo "  1. tailscale up --hostname phone --accept-dns=false   # open the URL, log in, Connect"
echo "  2. cat ~/.ssh/id_ed25519.pub   # add to the VPS ~/.ssh/authorized_keys"
echo "  3. reopen Termux, then:  vps   (ssh)   |   vnc   (tunnel for AVNC → localhost:5901)"
